#!/usr/bin/env -S bash -eux -o pipefail
#
# Small wrapper around guix, to setup GUIX_PATH before calling guix
# (and calling the (probably) right version of guix)

root="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"

user="$(logname 2>/dev/null || echo ${SUDO_USER:-${USER}})"
user_home=$(bash -c "cd ~$(printf %q "$user") && pwd")

export GUIX=${user_home}/.config/guix/current/bin/guix
export GUIX_PACKAGE_PATH="$root/modules${GUIX_PACKAGE_PATH:+:$GUIX_PACKAGE_PATH}"

exec "${GUIX}" "$@"
