#!/usr/bin/env -S bash -eux -o pipefail

root="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"

guix="$root/guix"

export HOME_CONF="$root/home.scm"

exec "${guix}" home "$@" -e '(@@ (fstamour home) %home)'
