#!/usr/bin/env -S bash -eux -o pipefail

root="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"

export GUIX=~/.config/guix/current/bin/guix
export GUIX_PACKAGE_PATH="$root/modules${GUIX_PACKAGE_PATH:+:$GUIX_PACKAGE_PATH}"

#host="$1"
#shift

if [ "${1:-}" = "reconfigure" ]; then
    exec sudo -E "${GUIX}" system "$@" \
         -e "(@@ (fstamour system) %hosts/$host)"
else
    exec "${GUIX}" system "$@" \
         -e "(@@ (fstamour system) %hosts/$host)"
fi
