#!/usr/bin/env -S bash -eux -o pipefail

root="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"

guix="$root/guix"

if [ "${1:-}" = "reconfigure" ]; then
    exec sudo -E "${guix}" system "$@" \
         -e "(@@ (fstamour system) %hosts/$host)"
else
    exec "${guix}" system "$@" \
         -e "(@@ (fstamour system) %hosts/$host)"
fi
