#!/usr/bin/env -S bash -eux -o pipefail
#
# Wrapper on "guix system" that tries to use the right "guix" and that
# uses my modules.
#
# Assumes it's running as root, and the hostname is hard-coded.

root="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"

export GUIX=guix
export GUIX_PACKAGE_PATH="$root/modules${GUIX_PACKAGE_PATH:+:$GUIX_PACKAGE_PATH}"

host=nu

exec "${GUIX}" system "$@" -e "(@@ (fstamour system) %hosts/$host)"
